### ISSUE TITLE
Using the same variable multiple times causes a bug

### ISSUE THREAD

**Issue by rlindner81** [cloudfoundry/multiapps#261] opened 2024-04-16 11:39 UTC
### Description

The problem can easily be described in a little example:

```yaml
_schema-version: 3.3.0
ID: mtaproblem
version: 1.0.0

parameters:
  global-param: ${space}${space}${space}

modules:
  - name: mtaproblem
    type: nodejs
    path: app
    properties:
      TEST: ${global-param}
```

This will fail to deploy regardless of the contents of app with
```
d057156@M12VHYH70W mtaproblem % cf deploy mta_archives/afc.mtar -f --version-rule ALL     
Deploying multi-target app archive mta_archives/afc.mtar in org skyfin / space debug as richard.lindner@sap.com...

Previously uploaded file afc.mtar with same digest detected, new upload will be skipped.
Operation ID: 9319bedc-fbe3-11ee-98f0-eeee0a9121f9
Deploying in org "skyfin" and space "debug"
Detected MTA schema version: "3"
No deployed MTA detected - this is initial deployment of MTA with ID "mtaproblem"
Detected new MTA version: "1.0.0"
Error resolving merged descriptor properties and parameters: Circular reference detected in "mtaproblem#TEST" 
Process failed.
```

In the deployment logs, we see slightly more:
```
Caused by: org.cloudfoundry.multiapps.common.ContentException: Circular reference detected in "mtaproblem#TEST"
	at org.cloudfoundry.multiapps.mta.resolvers.PropertiesResolver$ResolutionContext.addToReferencedKeys(PropertiesResolver.java:232) ~[multiapps-mta-2.20.0.jar:?]
	at org.cloudfoundry.multiapps.mta.resolvers.PropertiesResolver.visit(PropertiesResolver.java:68) ~[multiapps-mta-2.20.0.jar:?]
	at org.cloudfoundry.multiapps.mta.helpers.VisitableObject.acceptInternal(VisitableObject.java:57) ~[multiapps-mta-2.20.0.jar:?]
	at org.cloudfoundry.multiapps.mta.helpers.VisitableObject.accept(VisitableObject.java:34) ~[multiapps-mta-2.20.0.jar:?]
	at org.cloudfoundry.multiapps.mta.helpers.VisitableObject.accept(VisitableObject.java:20) ~[multiapps-mta-2.20.0.jar:?]
	at org.cloudfoundry.multiapps.mta.resolvers.PropertiesResolver.resolve(PropertiesResolver.java:62) ~[multiapps-mta-2.20.0.jar:?]
	at org.cloudfoundry.multiapps.mta.resolvers.PropertiesResolver.resolveReference(PropertiesResolver.java:133) ~[multiapps-mta-2.20.0.jar:?]
	at org.cloudfoundry.multiapps.mta.resolvers.PropertiesResolver.resolveReferenceInContext(PropertiesResolver.java:110) ~[multiapps-mta-2.20.0.jar:?]
	at org.cloudfoundry.multiapps.mta.resolvers.PropertiesResolver.resolveReferenceInPlace(PropertiesResolver.java:91) ~[multiapps-mta-2.20.0.jar:?]
	at org.cloudfoundry.multiapps.mta.resolvers.PropertiesResolver.resolveReferences(PropertiesResolver.java:80) ~[multiapps-mta-2.20.0.jar:?]
	at org.cloudfoundry.multiapps.mta.resolvers.PropertiesResolver.visit(PropertiesResolver.java:70) ~[multiapps-mta-2.20.0.jar:?]
```

There is no circular reference here, as can be seen, the visitor seems to have a problem if the same variable is used multiple times...

### Your environment
*	multiapps-mta - 2.20.0 (latest used by BTP's multiapps controller)
*	MultiApps CF CLI Plugin version - 3.2.2. (latest release as of writing)

### Steps to reproduce
See above

**Comment by ikasarov** [comment] 2024-09-27 10:08
Hi,
Sorry for the late reply. The issue is now fixed with the following commit, cheers.
https://github.com/cloudfoundry/multiapps/commit/10371925ec2b8b9915d52ffa905671f2dabccef4

**Closed by ikasarov** 2024-09-27 10:08 UTC
